### ISSUE TITLE
can't complete call to TLS_method

### ISSUE THREAD

**Issue by cup** [ikod/dlang-requests#106]
Using this file:

~~~d
import requests, std.stdio;
void main() {
   write(getContent("https://speed.hetzner.de"));
}
~~~

I get this result:

~~~
object.Exception@C:\Users\Steven\AppData\Local\dub\packages\requests-1.0.9\
requests\source\requests\ssl_adapter.d(249): can't complete call to TLS_method
~~~

**Comment by ikod** [comment]
Hello, @cup 

This error means that `requests` was unable to load ssl library.

Please, compile and run code and show me complete output.

```
import std.experimental.logger;
import requests;
void main() {
}
```

Also I need more info on your system (OS version, ssl library installed)

Thanks

**Comment by cup** [comment]
that source doesnt create any output...

**Comment by ikod** [comment]
Ok, what is your OS and openssl library installed?

**Comment by ikod** [comment]
Hello @cup 

Just in case you are on windows https://github.com/ikod/dlang-requests#windows-ssl-notes

**Comment by cup** [comment]
that link is not going to work for me as its a shared build. can you recommend a static build?

**Comment by ikod** [comment]
Hello @cup 

If you mean that you have to distribute executable to the machine where openssl library did not installed then sorry - no, you can't do this with `requests`

**Comment by cup** [comment]
@ikod are you certain? I found a static build here:

https://curl.haxx.se/windows

so I would just need a way to link it

**Comment by ikod** [comment]
@cup ,

If you will use std.net.curl in your code - then maybe yes, you can link ssl library statically(I never tried). 

But not with requests, because requests load ssl library dynamically during application start and detect openssl version at runtime (because openssl 1.0 and openssl 1.1 have different API and there is no easy and portable way to detect openssl version at library build time). You can find details here https://github.com/ikod/dlang-requests/issues/45 in case you interested.

**Comment by cup** [comment]
@ikod ok thank you, then I definitely cannot use requests.

**Comment by ikod** [comment]
Sorry for that, @cup
I'll close issue for now.
