### ISSUE TITLE
Empty responseBody on httpstat.us test pages

### ISSUE THREAD

**Issue by zorael** [ikod/dlang-requests#115]
Manjaro/Arch x86_64, dmd 2.090.0, requests 1.0.14.

When fetching a test page from `http://httpstat.us`, the `Response` struct has the appropriate code but the `responseBody` buffer is empty.

```d
Request req;
Response res = req.get("http://httpstat.us/500");
assert(res.code == 500);
writeln(res.responseBody);  // empty
```

Comparison:

```
$ curl http://httpstat.us/500
500 Internal Server Error
```

The curl command shows the response body doesn't end with a newline. Could that cause this?

**Comment by ikod** [comment]
Hello, @zorael 
Let me see what happens.

**Comment by ikod** [comment]
@zorael , running with `req.verbosity = 3` I see:
<pre>
Running ./t 
> GET /500 HTTP/1.1
> User-Agent: dlang-requests
> Host: httpstat.us
> Connection: Keep-Alive
> Accept-Encoding: gzip,deflate
> 
00000  48 54 54 50 2F 31 2E 31  20 35 30 30 20 49 6E 74  |HTTP/1.1 500 Int|
00010  65 72 6E 61 6C 20 53 65  72 76 65 72 20 45 72 72  |ernal Server Err|
00020  6F 72 0D 0A 43 61 63 68  65 2D 43 6F 6E 74 72 6F  |or..Cache-Contro|
00030  6C 3A 20 70 72 69 76 61  74 65 0D 0A 53 65 72 76  |l: private..Serv|
00040  65 72 3A 20 4D 69 63 72  6F 73 6F 66 74 2D 49 49  |er: Microsoft-II|
00050  53 2F 31 30 2E 30 0D 0A  58 2D 41 73 70 4E 65 74  |S/10.0..X-AspNet|
00060  4D 76 63 2D 56 65 72 73  69 6F 6E 3A 20 35 2E 31  |Mvc-Version: 5.1|
00070  0D 0A 41 63 63 65 73 73  2D 43 6F 6E 74 72 6F 6C  |..Access-Control|
00080  2D 41 6C 6C 6F 77 2D 4F  72 69 67 69 6E 3A 20 2A  |-Allow-Origin: *|
00090  0D 0A 58 2D 41 73 70 4E  65 74 2D 56 65 72 73 69  |..X-AspNet-Versi|
000A0  6F 6E 3A 20 34 2E 30 2E  33 30 33 31 39 0D 0A 52  |on: 4.0.30319..R|
000B0  65 71 75 65 73 74 2D 43  6F 6E 74 65 78 74 3A 20  |equest-Context: |
000C0  61 70 70 49 64 3D 63 69  64 2D 76 31 3A 37 35 38  |appId=cid-v1:758|
000D0  35 30 32 31 62 2D 32 64  62 37 2D 34 64 61 36 2D  |5021b-2db7-4da6-|
000E0  61 62 66 66 2D 32 63 66  32 33 30 30 35 66 30 61  |abff-2cf23005f0a|
000F0  39 0D 0A 41 63 63 65 73  73 2D 43 6F 6E 74 72 6F  |9..Access-Contro|
00100  6C 2D 45 78 70 6F 73 65  2D 48 65 61 64 65 72 73  |l-Expose-Headers|
00110  3A 20 52 65 71 75 65 73  74 2D 43 6F 6E 74 65 78  |: Request-Contex|
00120  74 0D 0A 58 2D 50 6F 77  65 72 65 64 2D 42 79 3A  |t..X-Powered-By:|
00130  20 41 53 50 2E 4E 45 54  0D 0A 53 65 74 2D 43 6F  | ASP.NET..Set-Co|
00140  6F 6B 69 65 3A 20 41 52  52 41 66 66 69 6E 69 74  |okie: ARRAffinit|
00150  79 3D 33 33 34 62 31 32  34 64 39 38 31 36 30 30  |y=334b124d981600|
00160  63 37 36 30 34 37 37 63  31 65 64 33 66 37 38 37  |c760477c1ed3f787|
00170  36 39 64 31 38 38 37 31  66 65 35 36 34 35 35 38  |69d18871fe564558|
00180  39 61 63 66 63 39 30 62  63 30 62 38 62 30 38 61  |9acfc90bc0b8b08a|
00190  34 39 3B 50 61 74 68 3D  2F 3B 48 74 74 70 4F 6E  |49;Path=/;HttpOn|
001A0  6C 79 3B 44 6F 6D 61 69  6E 3D 68 74 74 70 73 74  |ly;Domain=httpst|
001B0  61 74 2E 75 73 0D 0A 44  61 74 65 3A 20 53 61 74  |at.us..Date: Sat|
001C0  2C 20 31 35 20 46 65 62  20 32 30 32 30 20 32 30  |, 15 Feb 2020 20|
001D0  3A 34 34 3A 30 33 20 47  4D 54 0D 0A 43 6F 6E 74  |:44:03 GMT..Cont|
001E0  65 6E 74 2D 4C 65 6E 67  74 68 3A 20 30 0D 0A 0D  |ent-Length: 0...|
001F0  0A                                                |.               |
< HTTP/1.1 500 Internal Server Error
< cache-control: private
< server: Microsoft-IIS/10.0
< x-aspnetmvc-version: 5.1
< access-control-allow-origin: *
< x-aspnet-version: 4.0.30319
< request-context: appId=cid-v1:7585021b-2db7-4da6-abff-2cf23005f0a9
< access-control-expose-headers: Request-Context
< x-powered-by: ASP.NET
< set-cookie: ARRAffinity=334b124d981600c760477c1ed3f78769d18871fe5645589acfc90bc0b8b08a49;Path=/;HttpOnly;Domain=httpstat.us
< date: Sat, 15 Feb 2020 20:44:03 GMT
< content-length: 0
< 0 bytes of body received
>> Connect time: 264 ms, 380 μs, and 1 hnsec
>> Request send time: 226 μs and 9 hnsecs
>> Response recv time: 205 ms, 227 μs, and 5 hnsecs
</pre>
Please note <pre>content-length: 0</pre>

At the same time with curl:
<pre>
igor@igor-Zen:/tmp/t$ curl -o- -v http://httpstat.us/500
*   Trying 23.99.0.12...
* TCP_NODELAY set
* Connected to httpstat.us (23.99.0.12) port 80 (#0)
> GET /500 HTTP/1.1
> Host: httpstat.us
> User-Agent: curl/7.58.0
> Accept: */*
> 
< HTTP/1.1 500 Internal Server Error
< Cache-Control: private
< Content-Length: 25
< Content-Type: text/plain; charset=utf-8
< Server: Microsoft-IIS/10.0
< X-AspNetMvc-Version: 5.1
< Access-Control-Allow-Origin: *
< X-AspNet-Version: 4.0.30319
< Request-Context: appId=cid-v1:7585021b-2db7-4da6-abff-2cf23005f0a9
< Access-Control-Expose-Headers: Request-Context
< X-Powered-By: ASP.NET
< Set-Cookie: ARRAffinity=334b124d981600c760477c1ed3f78769d18871fe5645589acfc90bc0b8b08a49;Path=/;HttpOnly;Domain=httpstat.us
< Date: Sat, 15 Feb 2020 20:44:29 GMT
< 
* Connection #0 to host httpstat.us left intact

</pre>

So dlang-requests correctly shows no body.

Another question wtat is the difference with curl so that server send some body in response.

**Comment by zorael** [comment]
I see. Well, then it's not a requests bug, which is good.

Apologies for the noise.

**Comment by ikod** [comment]
@zorael 
No problem, you are welcome.
