### ISSUE TITLE
allow reading directly from buffer

### ISSUE THREAD

**Issue by yannick** [ikod/dlang-requests#19]
so that std.io.byChunk can be used on the data or directly.

e.g. provide a method `streamContent!buffsize`

**Comment by ikod** [comment]
Hello @yannick 
Rigth now I'm finishing what is called "streaming" in python-request(http://docs.python-requests.org/en/master/user/advanced/#body-content-workflow):
```
    ulong received;
    Request rq = Request();
    rq.useStreaming = true;
    auto rs = rq.get("https://httpbin.org/gzip");
    auto stream = rs.contentIterator();
    while( !stream.empty() ) {
        ubyte[] data = stream.front;
        received += data.length;
        writefln("Received %.2f of content", (rq.contentReceived*1e2)/rq.contentLength);
        stream.popFront();
    }
```
so that document body actually is lazy InputStream. Is it close to what you described?
If not - please explain.

**Comment by yannick** [comment]
It would be nicer to get direct access onto the content buffer slice from the socket to allow zerocopy operations. If stream.front is actually a reference and not a copy it might work.
Is your code online?

**Comment by ikod** [comment]
Yes, code is on github now, and example for streaming content is on the end of first page. You can check it,  I'll be thankful for any notes. 

But it is not zero-copy. Data from the socket collected to internal Buffer!ubyte, which is logically Appender!ubyte.
```
Buffer!ubyte appender;
ubyte[] buffer = new ubyte[bufferSize];
while( socket.opened) {
    read = _stream.receive(buffer);
    appender.put(buffer[0..read]);
}
```
appender.put() will copy data because input buffer can be reused. Moreover, un-compressing and un-chunking content will also copy. I will check and probably clean up something in this area after I will see all use cases for storing and accessing data.

**Comment by yannick** [comment]
hmm, i think the data gets copied too many times.
if its compressed you obviously need a 2nd (bigger) buffer. but each of the buffers should not be .dup'd on this level and allow raw access. 
so if i want to consume the stream API i should get read access to a buffer that is either the buffer from the socket OR the buffet from the decoder.

**Comment by ikod** [comment]
> hmm, i think the data gets copied too many times.

Agree. Have plan to look into this.

> btw: great library, its very useful, thank you a lot for porting it!

thanks!

**Comment by ikod** [comment]
@yannick 
Hello,

> hmm, i think the data gets copied too many times.
> if its compressed you obviously need a 2nd (bigger) buffer. but each of the buffers should not be .dup'd on this level and allow raw access.
> so if i want to consume the stream API i should get read access to a buffer that is either the buffer from the socket OR the buffet from the decoder.

Finally I cleaned up all unnecessary data moves.
For streaming mode: when no decompression involved, then application will receive socket data without any internal copy in most cases. In single case when you receive "chunked" content, and single socket read gives you parts from several chunks, then I join received parts, so that user code receive all available data in single call. Maybe I'll fix it too, but looks like this has no noticeable impact on performance.

For compressed content - looks like I have no any control over zlib buffers.
> 
> btw: great library, its very useful, thank you a lot for porting it!
> 

thanks, but to be clear - it is not a port, it is written just under influence.

**Comment by yannick** [comment]
cool! tried it, seems to work nicely
https://github.com/yannick/requests-asdf-example/blob/master/source/app.d

**Comment by ikod** [comment]
@yannick 
Very nice!
Btw, I'm thinking if it is possible somehow to use dlang-request inside vibe.d in non-blocking mode, as vibe.d http client looks unfriendly to me.

**Comment by yannick** [comment]
@ikod it could be possible but it requires streams.d to adapt to the eventloop and using vibe.ds internal ssl handling. 
you need to abstract away the fact that behind the back its callback based. 
look at: 
https://github.com/rejectedsoftware/vibe.d/blob/master/source/vibe/core/stream.d
and
https://github.com/rejectedsoftware/vibe.d/blob/master/source/vibe/http/client.d
i'm not an expert there though

**Comment by ikod** [comment]
@yannick I'll close this issue. Reopen please if something is not completed here.
